
ana = Team.create(division_id: 4, city: 'Anaheim', name: 'Ducks', abbrev: 'ana')
ari = Team.create(division_id: 4, city: 'Arizona', name: 'Coyotes', abbrev: 'ari')
cgy = Team.create(division_id: 4, city: 'Calgary', name: 'Flames', abbrev: 'cgy')
edm = Team.create(division_id: 4, city: 'Edmonton', name: 'Oilers', abbrev: 'edm')
van = Team.create(division_id: 4, city: 'Vancouver', name: 'Canucks', abbrev: 'van')
lak = Team.create(division_id: 4, city: 'Los Angeles', name: 'Kings', abbrev: 'lak')
sjs = Team.create(division_id: 4, city: 'San Jose', name: 'Sharks', abbrev: 'sjs')

chi = Team.create(division_id: 3, city: 'Chicago', name: 'Blackhawks', abbrev: 'chi')
col = Team.create(division_id: 3, city: 'Colorado', name: 'Avalanche', abbrev: 'col')
dal = Team.create(division_id: 3, city: 'Dallas', name: 'Stars', abbrev: 'dal')
min = Team.create(division_id: 3, city: 'Minnesota', name: 'Wild', abbrev: 'min')
nsh = Team.create(division_id: 3, city: 'Nashville', name: 'Predators', abbrev: 'nsh')
wpg = Team.create(division_id: 3, city: 'Winnipeg', name: 'Jets', abbrev: 'wpg')
stl = Team.create(division_id: 3, city: 'St. Louis', name: 'Blues', abbrev: 'stl')

bos = Team.create(division_id: 1, city: 'Boston', name: 'Bruins', abbrev: 'bos')
buf = Team.create(division_id: 1, city: 'Buffalo', name: 'Sabres', abbrev: 'buf')
fla = Team.create(division_id: 1, city: 'Florida', name: 'Panthers', abbrev: 'fla')
det = Team.create(division_id: 1, city: 'Detroit', name: 'Red Wings', abbrev: 'det')
mtl = Team.create(division_id: 1, city: 'Montreal', name: 'Canadiens', abbrev: 'mtl')
tor = Team.create(division_id: 1, city: 'Toronto', name: 'Maple Leafs', abbrev: 'tor')
tbl = Team.create(division_id: 1, city: 'Tampa Bay', name: 'Lightning', abbrev: 'tbl')
ott = Team.create(division_id: 1, city: 'Ottawa', name: 'Senators', abbrev: 'ott')

car = Team.create(division_id: 2, city: 'Carolina', name: 'Hurricanes', abbrev: 'car')
cbj = Team.create(division_id: 2, city: 'Columbus', name: 'Blue Jackets', abbrev: 'cbj')
phi = Team.create(division_id: 2, city: 'Philadelphia', name: 'Flyers', abbrev: 'phi')
pit = Team.create(division_id: 2, city: 'Pittsburgh', name: 'Penguins', abbrev: 'pit')
wsh = Team.create(division_id: 2, city: 'Washington', name: 'Capitals', abbrev: 'wsh')
njd = Team.create(division_id: 2, city: 'New Jersey', name: 'Devils', abbrev: 'njd')
nyi = Team.create(division_id: 2, city: 'New York', name: 'Islanders', abbrev: 'nyi')
nyr = Team.create(division_id: 2, city: 'New York', name: 'Rangers', abbrev: 'nyr')
